#!/bin/bash

# Generate the qmake makefile
qmake SmartCCTV_UI.pro
# Rename the qmake makefile
mv Makefile Makefile_qmake
# Rename/copy the skeleton makefile, set it as the real makefile,
# having a backup of the original copy.
cp Makefile_skeleton Makefile

# run a command(s) to replace all chunks of code that are labeled as FIXME in the skeleton makefile
# with corresponding chunks of code from the qmake generated makefile.
#
# In other words this command should:
#    Find all places in this skeleton makefile (Makefile) which are labeled as FIXME
#    inside the system-dependent makefile generated by qmake (Makefile_qmake) and copy
#    then over, replacing the corresponding text in the skeleton makefile (Makefile).

# Now your Makefile is complete!
# You can now run make to build the project!

